$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  adapter-read-1:
    type: string
  adapter-read-2:
    type: string

required:
  - samples
  - units
  - adapter-read-1
  - adapter-read-2
